devices:
  adjust_period: 5
  capture:
    channels: 2
    device: camilla_in
    format: S32LE
    retry_on_error: false
    type: Alsa
  capture_samplerate: 0
  chunksize: 4096
  enable_rate_adjust: false
  enable_resampling: false
  playback:
    channels: 2
    device: sound_out
    format: S16LE
    type: Alsa
  queuelimit: 4
  resampler_type: BalancedAsync
  samplerate: 44100
  silence_threshold: 0
  silence_timeout: 0
  target_level: 2048
filters:
  clipgain_L:
    parameters:
      gain: 0
      inverted: false
      mute: false
    type: Gain
  clipgain_R:
    parameters:
      gain: 0
      inverted: false
      mute: false
    type: Gain
mixers: {}
pipeline:
- channel: 0
  names:
  - clipgain_L
  type: Filter
- channel: 1
  names:
  - clipgain_R
  type: Filter
